name: deploy

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - run: npm install
    - name: Publish
      if: startsWith( github.ref, 'refs/tags/releases/')
      run: npm run deploy
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
